### ISSUE TITLE
PLano de gerenciamento de Qualidade

### ISSUE THREAD

**Issue by Mateusas3s** [PI2-GRUPO5-DAC-CO2/Documentacao-Artefatos#17]
1. Defina o Título da Issue
2. Descreva brevemente a Issue (podem ser adicionadas imagens)
3. Descreva as tarefas quesitos para finalizar a Issue
4. Classifique a Issue na opção Labels
5. Marque os responsáveis na opção Assignees

Descrever plano definido para monitoramento e controle da qualidade das ativiades realaizadas:

- [x] Definir papeis de validadores e inspetores
- [x] Definir dinâmica de validação e inspeção
- [x] Descrever no relatório de plano de controle

**Comment by marcelostosjr** [comment]
comecei a desenvolver
