### ISSUE TITLE
Planilha de Cálculos Estequiométricos

### ISSUE THREAD

**Issue by NadiaSales9** [PI2-GRUPO5-DAC-CO2/Documentacao-Artefatos#19]
- [x] Criar planilha que facilite a modificação dos parâmetros;

Link de refência para o cálculo: 
- https://www.cell.com/joule/fulltext/S2542-4351(18)30225-3 
- http://plataforma.seeg.eco.br/sectors/energia

**Comment by Mateusas3s** [comment]
Lembrar de compartilhar o link da planilha quando já tiver uma versão primária

**Comment by NadiaSales9** [comment]
Link da planilha: https://drive.google.com/file/d/1z8hyGxACh8x20TNibdbl5tbQbF2SE4LV/view?usp=sharing
