### ISSUE TITLE
Protótipo de alta fidelidade

### ISSUE THREAD

**Issue by Rdadamos** [PI2-GRUPO5-DAC-CO2/Documentacao-Artefatos#26]
Elaborar protótipo de alta fidelidade com as seguintes telas:
[x] cadastro
[x] login
[x] tela inicial (home)

**Comment by roginaldosemog** [comment]
Feito!

[Visualizar protótipo](https://www.figma.com/file/EbJexfdEm0DIBTlOCYwa12/CATARCO?node-id=0%3A1).
